server:
  port: 8085
  servlet:
    context-path: /realman-iot

spring:
  application:
    name: realman-iot
  config:
    import: optional:classpath:config/application-liteflow.yml
  profiles:
    active: '@profile.name@'